package net.arver.mall.goods.mapper;

import java.util.List;
import net.arver.mall.goods.model.CategoryBrand;
import net.arver.mall.goods.model.CategoryBrandExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CategoryBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @SelectProvider(type=CategoryBrandSqlProvider.class, method="countByExample")
    long countByExample(CategoryBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @DeleteProvider(type=CategoryBrandSqlProvider.class, method="deleteByExample")
    int deleteByExample(CategoryBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Delete({
        "delete from tb_category_brand",
        "where category_id = #{categoryId,jdbcType=INTEGER}",
          "and brand_id = #{brandId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("categoryId") Integer categoryId, @Param("brandId") Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Insert({
        "insert into tb_category_brand (category_id, brand_id)",
        "values (#{categoryId,jdbcType=INTEGER}, #{brandId,jdbcType=INTEGER})"
    })
    int insert(CategoryBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @InsertProvider(type=CategoryBrandSqlProvider.class, method="insertSelective")
    int insertSelective(CategoryBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @SelectProvider(type=CategoryBrandSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<CategoryBrand> selectByExample(CategoryBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @UpdateProvider(type=CategoryBrandSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CategoryBrand record, @Param("example") CategoryBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @UpdateProvider(type=CategoryBrandSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CategoryBrand record, @Param("example") CategoryBrandExample example);
}
