package net.arver.mall.goods.mapper;

import java.util.List;
import java.util.Map;
import net.arver.mall.goods.model.Pref;
import net.arver.mall.goods.model.PrefExample.Criteria;
import net.arver.mall.goods.model.PrefExample.Criterion;
import net.arver.mall.goods.model.PrefExample;
import org.apache.ibatis.jdbc.SQL;

public class PrefSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String countByExample(PrefExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_pref");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String deleteByExample(PrefExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_pref");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String insertSelective(Pref record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_pref");

        if (record.getCateId() != null) {
            sql.VALUES("cate_id", "#{cateId,jdbcType=INTEGER}");
        }

        if (record.getBuyMoney() != null) {
            sql.VALUES("buy_money", "#{buyMoney,jdbcType=INTEGER}");
        }

        if (record.getPreMoney() != null) {
            sql.VALUES("pre_money", "#{preMoney,jdbcType=INTEGER}");
        }

        if (record.getStartTime() != null) {
            sql.VALUES("start_time", "#{startTime,jdbcType=DATE}");
        }

        if (record.getEndTime() != null) {
            sql.VALUES("end_time", "#{endTime,jdbcType=DATE}");
        }

        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=CHAR}");
        }

        if (record.getState() != null) {
            sql.VALUES("state", "#{state,jdbcType=CHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String selectByExample(PrefExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cate_id");
        sql.SELECT("buy_money");
        sql.SELECT("pre_money");
        sql.SELECT("start_time");
        sql.SELECT("end_time");
        sql.SELECT("type");
        sql.SELECT("state");
        sql.FROM("tb_pref");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Pref record = (Pref) parameter.get("record");
        PrefExample example = (PrefExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("tb_pref");

        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }

        if (record.getCateId() != null) {
            sql.SET("cate_id = #{record.cateId,jdbcType=INTEGER}");
        }

        if (record.getBuyMoney() != null) {
            sql.SET("buy_money = #{record.buyMoney,jdbcType=INTEGER}");
        }

        if (record.getPreMoney() != null) {
            sql.SET("pre_money = #{record.preMoney,jdbcType=INTEGER}");
        }

        if (record.getStartTime() != null) {
            sql.SET("start_time = #{record.startTime,jdbcType=DATE}");
        }

        if (record.getEndTime() != null) {
            sql.SET("end_time = #{record.endTime,jdbcType=DATE}");
        }

        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=CHAR}");
        }

        if (record.getState() != null) {
            sql.SET("state = #{record.state,jdbcType=CHAR}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_pref");

        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cate_id = #{record.cateId,jdbcType=INTEGER}");
        sql.SET("buy_money = #{record.buyMoney,jdbcType=INTEGER}");
        sql.SET("pre_money = #{record.preMoney,jdbcType=INTEGER}");
        sql.SET("start_time = #{record.startTime,jdbcType=DATE}");
        sql.SET("end_time = #{record.endTime,jdbcType=DATE}");
        sql.SET("type = #{record.type,jdbcType=CHAR}");
        sql.SET("state = #{record.state,jdbcType=CHAR}");

        PrefExample example = (PrefExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String updateByPrimaryKeySelective(Pref record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_pref");

        if (record.getCateId() != null) {
            sql.SET("cate_id = #{cateId,jdbcType=INTEGER}");
        }

        if (record.getBuyMoney() != null) {
            sql.SET("buy_money = #{buyMoney,jdbcType=INTEGER}");
        }

        if (record.getPreMoney() != null) {
            sql.SET("pre_money = #{preMoney,jdbcType=INTEGER}");
        }

        if (record.getStartTime() != null) {
            sql.SET("start_time = #{startTime,jdbcType=DATE}");
        }

        if (record.getEndTime() != null) {
            sql.SET("end_time = #{endTime,jdbcType=DATE}");
        }

        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=CHAR}");
        }

        if (record.getState() != null) {
            sql.SET("state = #{state,jdbcType=CHAR}");
        }

        sql.WHERE("id = #{id,jdbcType=INTEGER}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pref
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    protected void applyWhere(SQL sql, PrefExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
