package net.arver.mall.goods.mapper;

import java.util.List;
import net.arver.mall.goods.model.Sku;
import net.arver.mall.goods.model.SkuExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @SelectProvider(type=SkuSqlProvider.class, method="countByExample")
    long countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @DeleteProvider(type=SkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Delete({
        "delete from tb_sku",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Insert({
        "insert into tb_sku (sn, name, ",
        "price, num, alert_num, ",
        "image, images, weight, ",
        "create_time, update_time, ",
        "spu_id, category_id, ",
        "category_name, brand_name, ",
        "spec, sale_num, comment_num, ",
        "status)",
        "values (#{sn,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=INTEGER}, #{num,jdbcType=INTEGER}, #{alertNum,jdbcType=INTEGER}, ",
        "#{image,jdbcType=VARCHAR}, #{images,jdbcType=VARCHAR}, #{weight,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{spuId,jdbcType=VARCHAR}, #{categoryId,jdbcType=INTEGER}, ",
        "#{categoryName,jdbcType=VARCHAR}, #{brandName,jdbcType=VARCHAR}, ",
        "#{spec,jdbcType=VARCHAR}, #{saleNum,jdbcType=INTEGER}, #{commentNum,jdbcType=INTEGER}, ",
        "#{status,jdbcType=CHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @InsertProvider(type=SkuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @SelectProvider(type=SkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sn", property="sn", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="alert_num", property="alertNum", jdbcType=JdbcType.INTEGER),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="images", property="images", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="sale_num", property="saleNum", jdbcType=JdbcType.INTEGER),
        @Result(column="comment_num", property="commentNum", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR)
    })
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Select({
        "select",
        "id, sn, name, price, num, alert_num, image, images, weight, create_time, update_time, ",
        "spu_id, category_id, category_name, brand_name, spec, sale_num, comment_num, ",
        "status",
        "from tb_sku",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sn", property="sn", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="alert_num", property="alertNum", jdbcType=JdbcType.INTEGER),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="images", property="images", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="sale_num", property="saleNum", jdbcType=JdbcType.INTEGER),
        @Result(column="comment_num", property="commentNum", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR)
    })
    Sku selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @UpdateProvider(type=SkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @UpdateProvider(type=SkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @UpdateProvider(type=SkuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Update({
        "update tb_sku",
        "set sn = #{sn,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=INTEGER},",
          "num = #{num,jdbcType=INTEGER},",
          "alert_num = #{alertNum,jdbcType=INTEGER},",
          "image = #{image,jdbcType=VARCHAR},",
          "images = #{images,jdbcType=VARCHAR},",
          "weight = #{weight,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "spu_id = #{spuId,jdbcType=VARCHAR},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "brand_name = #{brandName,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "sale_num = #{saleNum,jdbcType=INTEGER},",
          "comment_num = #{commentNum,jdbcType=INTEGER},",
          "status = #{status,jdbcType=CHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Sku record);
}
