package net.arver.mall.goods.model;

import java.io.Serializable;

public class Album implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.title
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.image_items
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String imageItems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_album
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.id
     *
     * @return the value of tb_album.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.id
     *
     * @param id the value for tb_album.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.title
     *
     * @return the value of tb_album.title
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.title
     *
     * @param title the value for tb_album.title
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.image
     *
     * @return the value of tb_album.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.image
     *
     * @param image the value for tb_album.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.image_items
     *
     * @return the value of tb_album.image_items
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getImageItems() {
        return imageItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.image_items
     *
     * @param imageItems the value for tb_album.image_items
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setImageItems(String imageItems) {
        this.imageItems = imageItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", image=").append(image);
        sb.append(", imageItems=").append(imageItems);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}