package net.arver.mall.goods.model;

import java.io.Serializable;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.goods_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_show
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_menu
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String isMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.seq
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.parent_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.template_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_category
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.id
     *
     * @return the value of tb_category.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.id
     *
     * @param id the value for tb_category.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.name
     *
     * @return the value of tb_category.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.name
     *
     * @param name the value for tb_category.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.goods_num
     *
     * @return the value of tb_category.goods_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.goods_num
     *
     * @param goodsNum the value for tb_category.goods_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_show
     *
     * @return the value of tb_category.is_show
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_show
     *
     * @param isShow the value for tb_category.is_show
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_menu
     *
     * @return the value of tb_category.is_menu
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_menu
     *
     * @param isMenu the value for tb_category.is_menu
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setIsMenu(String isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.seq
     *
     * @return the value of tb_category.seq
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.seq
     *
     * @param seq the value for tb_category.seq
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.parent_id
     *
     * @return the value of tb_category.parent_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.parent_id
     *
     * @param parentId the value for tb_category.parent_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.template_id
     *
     * @return the value of tb_category.template_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.template_id
     *
     * @param templateId the value for tb_category.template_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", goodsNum=").append(goodsNum);
        sb.append(", isShow=").append(isShow);
        sb.append(", isMenu=").append(isMenu);
        sb.append(", seq=").append(seq);
        sb.append(", parentId=").append(parentId);
        sb.append(", templateId=").append(templateId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}