package net.arver.mall.goods.model;

import java.io.Serializable;
import java.util.Date;

public class Sku implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.sn
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.price
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.alert_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer alertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.images
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.weight
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.update_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.spu_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.category_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.category_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.brand_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.spec
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.sale_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer saleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.comment_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sku.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.id
     *
     * @return the value of tb_sku.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.id
     *
     * @param id the value for tb_sku.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.sn
     *
     * @return the value of tb_sku.sn
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.sn
     *
     * @param sn the value for tb_sku.sn
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.name
     *
     * @return the value of tb_sku.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.name
     *
     * @param name the value for tb_sku.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.price
     *
     * @return the value of tb_sku.price
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.price
     *
     * @param price the value for tb_sku.price
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.num
     *
     * @return the value of tb_sku.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.num
     *
     * @param num the value for tb_sku.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.alert_num
     *
     * @return the value of tb_sku.alert_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getAlertNum() {
        return alertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.alert_num
     *
     * @param alertNum the value for tb_sku.alert_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setAlertNum(Integer alertNum) {
        this.alertNum = alertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.image
     *
     * @return the value of tb_sku.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.image
     *
     * @param image the value for tb_sku.image
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.images
     *
     * @return the value of tb_sku.images
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.images
     *
     * @param images the value for tb_sku.images
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.weight
     *
     * @return the value of tb_sku.weight
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.weight
     *
     * @param weight the value for tb_sku.weight
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.create_time
     *
     * @return the value of tb_sku.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.create_time
     *
     * @param createTime the value for tb_sku.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.update_time
     *
     * @return the value of tb_sku.update_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.update_time
     *
     * @param updateTime the value for tb_sku.update_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.spu_id
     *
     * @return the value of tb_sku.spu_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.spu_id
     *
     * @param spuId the value for tb_sku.spu_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSpuId(String spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.category_id
     *
     * @return the value of tb_sku.category_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.category_id
     *
     * @param categoryId the value for tb_sku.category_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.category_name
     *
     * @return the value of tb_sku.category_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.category_name
     *
     * @param categoryName the value for tb_sku.category_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.brand_name
     *
     * @return the value of tb_sku.brand_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.brand_name
     *
     * @param brandName the value for tb_sku.brand_name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.spec
     *
     * @return the value of tb_sku.spec
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.spec
     *
     * @param spec the value for tb_sku.spec
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.sale_num
     *
     * @return the value of tb_sku.sale_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.sale_num
     *
     * @param saleNum the value for tb_sku.sale_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.comment_num
     *
     * @return the value of tb_sku.comment_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.comment_num
     *
     * @param commentNum the value for tb_sku.comment_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sku.status
     *
     * @return the value of tb_sku.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sku.status
     *
     * @param status the value for tb_sku.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sku
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sn=").append(sn);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", num=").append(num);
        sb.append(", alertNum=").append(alertNum);
        sb.append(", image=").append(image);
        sb.append(", images=").append(images);
        sb.append(", weight=").append(weight);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", spuId=").append(spuId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", brandName=").append(brandName);
        sb.append(", spec=").append(spec);
        sb.append(", saleNum=").append(saleNum);
        sb.append(", commentNum=").append(commentNum);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}