package net.arver.mall.goods.model;

import java.io.Serializable;
import java.util.Date;

public class StockBack implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.order_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.sku_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock_back.back_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Date backTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_stock_back
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.order_id
     *
     * @return the value of tb_stock_back.order_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.order_id
     *
     * @param orderId the value for tb_stock_back.order_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.sku_id
     *
     * @return the value of tb_stock_back.sku_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.sku_id
     *
     * @param skuId the value for tb_stock_back.sku_id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.num
     *
     * @return the value of tb_stock_back.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.num
     *
     * @param num the value for tb_stock_back.num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.status
     *
     * @return the value of tb_stock_back.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.status
     *
     * @param status the value for tb_stock_back.status
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.create_time
     *
     * @return the value of tb_stock_back.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.create_time
     *
     * @param createTime the value for tb_stock_back.create_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock_back.back_time
     *
     * @return the value of tb_stock_back.back_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Date getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock_back.back_time
     *
     * @param backTime the value for tb_stock_back.back_time
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setBackTime(Date backTime) {
        this.backTime = backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock_back
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", skuId=").append(skuId);
        sb.append(", num=").append(num);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", backTime=").append(backTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}