package net.arver.mall.goods.model;

import java.io.Serializable;

public class Template implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_template.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_template.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_template.spec_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer specNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_template.para_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private Integer paraNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_template
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_template.id
     *
     * @return the value of tb_template.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_template.id
     *
     * @param id the value for tb_template.id
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_template.name
     *
     * @return the value of tb_template.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_template.name
     *
     * @param name the value for tb_template.name
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_template.spec_num
     *
     * @return the value of tb_template.spec_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getSpecNum() {
        return specNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_template.spec_num
     *
     * @param specNum the value for tb_template.spec_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setSpecNum(Integer specNum) {
        this.specNum = specNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_template.para_num
     *
     * @return the value of tb_template.para_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public Integer getParaNum() {
        return paraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_template.para_num
     *
     * @param paraNum the value for tb_template.para_num
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    public void setParaNum(Integer paraNum) {
        this.paraNum = paraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_template
     *
     * @mbg.generated Wed Jul 08 23:31:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", specNum=").append(specNum);
        sb.append(", paraNum=").append(paraNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}